/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.MineBank.app.view;

import com.MineBank.app.Enums.TransactionType;
import com.MineBank.app.model.User;
import com.MineBank.app.utils.Utils;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JTextField;

/**
 *
 * @author giann
 */
public class TransactionAmtView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TransactionAmtView.class.getName());

    
    /**
     * Creates new form TransactionAmtView
     */
    
    private TransactionType type;
    
    public TransactionAmtView(TransactionType type) {
        this.type = type;
        initComponents();
        renderTransactionType();
        processInput();
        setIconImage(new ImageIcon(DisplaysUtils.programIcon).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        trnTypeHeader = new javax.swing.JLabel();
        amountField = new javax.swing.JTextField();
        accNumLabel = new javax.swing.JLabel();
        balanceLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        trnTypeButton = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        invalidNumLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Withdraw");

        jPanel1.setBackground(new java.awt.Color(255, 250, 239));
        jPanel1.setPreferredSize(new java.awt.Dimension(460, 520));

        trnTypeHeader.setBackground(new java.awt.Color(29, 126, 190));
        trnTypeHeader.setFont(new java.awt.Font("minecrafter", 0, 36)); // NOI18N
        trnTypeHeader.setForeground(new java.awt.Color(0, 0, 0));
        trnTypeHeader.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        trnTypeHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/income-36px.png"))); // NOI18N
        trnTypeHeader.setText("Transaction");
        trnTypeHeader.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        amountField.setBackground(new java.awt.Color(255, 250, 239));
        amountField.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        amountField.setForeground(new java.awt.Color(51, 51, 51));
        amountField.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10)));
        amountField.setMargin(new java.awt.Insets(2, 20, 2, 10));
        amountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountFieldActionPerformed(evt);
            }
        });

        accNumLabel.setBackground(new java.awt.Color(0, 0, 0));
        accNumLabel.setFont(new java.awt.Font("Minecraft", 0, 14)); // NOI18N
        accNumLabel.setForeground(new java.awt.Color(91, 91, 91));
        accNumLabel.setText("Account Number: <null>");

        balanceLabel.setBackground(new java.awt.Color(0, 0, 0));
        balanceLabel.setFont(new java.awt.Font("Minecraft", 0, 14)); // NOI18N
        balanceLabel.setForeground(new java.awt.Color(91, 91, 91));
        balanceLabel.setText("Balance: <null>");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/emerald-40px.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Minecraft", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(91, 91, 91));
        jLabel5.setText("Amount:");

        trnTypeButton.setBackground(new java.awt.Color(204, 213, 174));
        trnTypeButton.setFont(new java.awt.Font("Minecraft", 0, 12)); // NOI18N
        trnTypeButton.setForeground(new java.awt.Color(30, 30, 30));
        trnTypeButton.setText("Type");
        trnTypeButton.setMargin(new java.awt.Insets(6, 14, 3, 14));
        trnTypeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trnTypeButtonActionPerformed(evt);
            }
        });

        cancelBtn.setBackground(new java.awt.Color(172, 172, 172));
        cancelBtn.setFont(new java.awt.Font("Minecraft", 0, 12)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(30, 30, 30));
        cancelBtn.setText("Cancel");
        cancelBtn.setMargin(new java.awt.Insets(6, 14, 3, 14));
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        invalidNumLabel.setFont(new java.awt.Font("Minecraft", 0, 12)); // NOI18N
        invalidNumLabel.setForeground(new java.awt.Color(189, 14, 14));
        invalidNumLabel.setText("Please enter a valid number!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(accNumLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(balanceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(amountField)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(trnTypeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 191, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(trnTypeHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(invalidNumLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(trnTypeHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accNumLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(balanceLabel)
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(invalidNumLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trnTypeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void amountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountFieldActionPerformed
        trnTypeButton.doClick();
    }//GEN-LAST:event_amountFieldActionPerformed

    private void trnTypeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trnTypeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trnTypeButtonActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelBtnActionPerformed

    
    private void renderTransactionType() {
        String trnTypeStr = Utils.toProperCase(type.name());
        trnTypeHeader.setText(trnTypeStr);
        trnTypeButton.setText(trnTypeStr);
    }
    
    public void setTransactionBtnAction(ActionListener listener) {
        trnTypeButton.addActionListener(listener);
    }
    
    public void setCancelBtnAction(ActionListener listener) {
        cancelBtn.addActionListener(listener);
    }
    
    // block non-number cgaracters
    private void processInput() {
        invalidNumLabel.setVisible(false);
        
        amountField.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                JTextField field = (JTextField) e.getSource();
                
                if (!Character.isDigit(c) && c != '.' && c != '\b') {
                    e.consume();
                    invalidNumLabel.setText("Please enter a valid number!");
                    invalidNumLabel.setVisible(true);
                } else {
                    invalidNumLabel.setVisible(false);
                }
                
                if (c == '.' && field.getText().contains(".")) {
                    e.consume();
                    invalidNumLabel.setText("Number cannot contain multiple decimal points!");
                    invalidNumLabel.setVisible(true);
                }
            }
        });
    }
    
    public void renderUserInfo(User user) {
        accNumLabel.setText("Account Number: " + user.getAccNum());
        balanceLabel.setText("Balance: " + DisplaysUtils.formatAmount(user.getBalance()) + " emeralds");
    }
    
    public String getInputAmountStr() {
        return amountField.getText().trim();
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accNumLabel;
    private javax.swing.JTextField amountField;
    private javax.swing.JLabel balanceLabel;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel invalidNumLabel;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton trnTypeButton;
    private javax.swing.JLabel trnTypeHeader;
    // End of variables declaration//GEN-END:variables
}
